services:
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - database
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
      - "mysql_data:/var/lib/mysql"

  workspace:
    image: evadonardem/php-apache-8.3.2:latest
    domainname: localhost
    hostname: dev
    depends_on:
      - mysql
    networks:
      database:
      mailpit:
    ports:
      - "8080:80"
      - "5173:5173"
    tty: true
    volumes:
      - '.:/var/www/html'

  mailpit:
    image: axllent/mailpit:latest
    networks:
      - mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

# Volumes setup
volumes:
  mysql_data:

# Networks setup
networks:
  database:
  mailpit:
